# Generated by Django 5.2.7 on 2026-03-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_chatsession_options_chatmessage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
    ]
